name: CI

on:
  push:
    branches:
      - master

env:
  CI: true

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test-Jest
        run: npm run test:jest

      - name: Test-Cypress
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          # build: npx cypress info
          wait-on: "http://localhost:3000"
          wait-on-timeout: 60

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
